name: 'Config Report Features'
type: module
core: 8.x
dependencies:
  - ckeditor
  - ckeditor_media_embed
  - editor
  - editor_file
  - entity_embed
  - filter
  - video_embed_wysiwyg
version: 8.x-1.0
