better_messages.settings:
  type: config_entity
  label: 'Better Messages settings'
  mapping:
    position:
      type: string
      label: 'Position'
    vertical:
      type: integer
      label: 'Vertical'
    horizontal:
      type: integer
      label: 'Horizontal'
    fixed:
      type: integer
      label: 'Fixed'
    width:
      type: string
      label: 'Width'
    autoclose:
      type: integer
      label: 'autoclose'
    opendelay:
      type: float
      label: 'Opendelay'
    disable_autoclose:
      type: integer
      label: 'Disable autoclose'
    show_countdown:
      type: integer
      label: 'Show countdown'
    hover_autoclose:
      type: integer
      label: 'Hover autoclose'
    popin:
      type: mapping
      label: 'Popin effect'
      mapping:
        effect:
          type: string
          label: 'Effect'
        duration:
          type: string
          label: 'Duration'
    popout:
      type: mapping
      label: 'Popout effect'
      mapping:
        effect:
          type: string
          label: 'Effect'
        duration:
          type: string
          label: 'Duration'
    jquery_ui:
      type: mapping
      label: 'jQuery UI enhancement'
      mapping:
        draggable:
          type: integer
          label: 'Draggable'
        resizable :
          type: integer
          label: 'Resizable'
    visibility:
      type: sequence
      label: 'Visibility Conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Visibility Condition'
